### ISSUE TITLE
Silently fails without showing error output

### ISSUE THREAD

**Issue by songty** [botandrose/eboshi_api_shootout#48]
@mradamh and @ageoldpun I'm seeing silently go on indefinitely without any error outputs. Closer inspection shows issues with bootstrapping the DB. Paul is also having a similar issue with

`ERROR 1292 (22007) at line 1: Incorrect datetime value: '2006-06-25T14:08:31Z' for column 'created_at' at row 1`

**Comment by botandrose** [comment]
So was the consensus that the Z is not required for UTC timestamps?

**Comment by songty** [comment]
Timezone might require its separate column

**Comment by mradamh** [comment]
A wild Tian appears!

I looked more into mysql datetime formats, and it looks like the 'Z' is actually prohibited in datetime literals - timezone is not stored in a datetime field.  there must be something in the stack that is doing some kind of conversion on linux but not os x.

https://dev.mysql.com/doc/refman/5.1/en/date-and-time-literals.html

So I think I was wrong originally to ask for the zulu stamp to be added.

**Comment by mradamh** [comment]
> Timezone might require its separate column

I think timezone should not be relevant here, the stamp is always assumed UTC.  API should *only* communicate in UTC.

**Comment by botandrose** [comment]
Roger that! IIRC, removing the Z had no adverse effects, so I'll remove it again.

**Comment by botandrose** [comment]
Closed by 2943b70. Renaming this to `MySQL Zulu, Yea or Nay`, and gonna split the silently bug off into a new issue.
