### ISSUE TITLE
Silently fails without showing error output

### ISSUE THREAD

**Issue by botandrose** [botandrose/eboshi_api_shootout#49]
If the server fails on startup, `silently` swallows the error.

**Comment by BartMassey** [comment]
Is this Haskell Scotty or something else? Whose `silently` are we talking about?

**Comment by botandrose** [comment]
It's a small shell function I wrote to hide output if it's successful, but show it if it's not. The problem is when its run against a process, which may spew important debugging info before we receive an exit code. Gonna have to rethink my strategy.
