### ISSUE TITLE
Organization and git submodules for this project?

### ISSUE THREAD

**Issue by BartMassey** [botandrose/eboshi_api_shootout#50]
Having all the implementations of *eboshi_api* in a single git repo has both positive and negative consequences. All the code in one repo adds some convenience and provides global visibility. On the other hand, it makes merge/rebase issues worse and makes it harder to tell which issues belong to which project. Using a GitHub organization and a `git submodule` structure with a separate repo for each  server implementation seems nicer to me. Failing that, it would be nice to add per-project issue tracker tags, but the merge/rebase problem seems annoying. Basically, I'd just like to be able to work on the Haskell Scotty code without worrying about the rest of it.

Thoughts?

**Comment by botandrose** [comment]
Submodules have put a terrible taste in my mouth. It's possible that
they've improved since I last tried them, but for the moment I'm more
inclined to be able to whitelist or blacklist impls you care or don't care
about. For the moment, i think you can simply not run `make`, and instead,
just only run `make haskell_scotty`. What do you think?

**Comment by botandrose** [comment]
Forgot to mention, aside from the test suite, all impls should be
completely independent.

**Comment by BartMassey** [comment]
It's not about runtime, it's about repo management. As it stands, I'm tracking, merging and rebasing every implementation here. And I'm trying to figure out which issues I care about.

Your call. Submodules have issues, but I haven't found them unusable. But they have issues.

**Comment by mradamh** [comment]
I'd also like to avoid submodules.  My preference would be to manage attention by custom labels for implementation names.

**Comment by botandrose** [comment]
I agree that labelling issues and PRs with per-impl tags is a good idea. Let's do it.

With regards to dealing with commits from other impls, it seems to me that rebasing and/or merging commits from other impls should be transparent, if you're not touching any of that code. Shouldn't be any merge conflicts. Just periodically ff merge master, and Bob's your uncle, right? Or are you saying that the list of commits is full of uninteresting noise if you're just trying to keep up with one impl? Trying to understand your pain point.

If that's the case, I'm interested in all the commits from all the impls, personally, so my viewpoint is different, here. But I think git provides options to `log` and `diff` and friends to filter by subtree, which may help.

**Comment by BartMassey** [comment]
I am fine with seeing all the commits go by. I just would prefer to avoid rebasing and merging whenever possible; these actions are error-prone and hassleful even when they turn out to be fast-forward. Separate repos would lead to a simple pull-work-push model for the most part: maybe we can get this without that, in which case I'm fine with it. I think I was partly just a victim of the head-bashing you did and got confused about how I was out of sync. :-)

**Comment by botandrose** [comment]
Ah, I understand. If you follow the development guidelines I just laid out in #53, I expect development will be harmonious. Closing, feel free to reopen if there are still pain points. Will also label all PRs and Issues presently.
