### ISSUE TITLE
Don't know how to set up a test database

### ISSUE THREAD

**Issue by BartMassey** [botandrose/eboshi_api_shootout#58]
It looks like there's some framework support for populating a test database, but it's not obvious how to use it.

**Comment by botandrose** [comment]
Just set the environment variables detailed at the bottom of the readme, and let make take care of the rest.

If you're interested in the details, there is no framework used for the tests... I've striven to have the entire suite be simple Ruby code with no external dependencies for maximum readability.

**Comment by botandrose** [comment]
Don't even need to set the environment variables if you're happy with the defaults.

**Comment by botandrose** [comment]
WDYT? Perhaps the README could be improved to better communicate this?

**Comment by botandrose** [comment]
Thinking about this some more, I guess one could definitely classify the test suite and `make` infrastructure to be a framework. After all, it calls the impls, the impls don't call it.

**Comment by BartMassey** [comment]
Still not getting it here. I don't seem to automatically get any customer records in the test database, which seems wrong to me?

**Comment by botandrose** [comment]
Oh, I see. You are wanting a mechanism for inserting example data into the db so you can toy with the server outside the context of the test suite. There is nothing like that in the codebase, at present... the primary means of interacting with the server is via the test suite. Also, note that the test suite empties the database on every test case, so the contents of the `eboshi_test` database at any given time should be considered transient, so if you wanted to play with the server outside the context of the test suite, I'd recommend booting the server with a different db name, i.e. just `eboshi`.
