### ISSUE TITLE
Licensing and Copyright?

### ISSUE THREAD

**Issue by BartMassey** [botandrose/eboshi_api_shootout#67]
Do we want this under an open source license? (If it is in a public Git repo, I think this is required.) If so, which one? (I don't really care. I'd probably choose GPLv3, with MIT my second choice.) In any case, someone needs to put a license on this, whether open source or no.

All the files should have copyright notices as well. I'm happy to slap them on, but again tell me whether you want me to guess from git history who wrote what, or whether you want to make the whole project copyright *Bot and Rose.* (Again, I don't care.)

I usually use my [apply-license](/BartMassey/apply-license) scripts to do this stuff, so I'm happy to do the work, if someone tells me what they want.

**Comment by botandrose** [comment]
I'll add a LICENSE file and a License section to the README, and I think that's good enough. Everything else I've done is MIT, so let's go with that.
