### ISSUE TITLE
Clojure Liberator server does not respond to SIGINT when backgrounded

### ISSUE THREAD

**Issue by botandrose** [botandrose/eboshi_api_shootout#73]
Clojure liberator impl's server ignores SIGINT when backgrounded, but responds properly when run in the foreground. Bug in Clojure or Jetty?

Temporarily worked around in https://github.com/botandrose/eboshi_api_shootout/commit/f1939268ee567bed5f37e1df363df38473073390 . Revert when this issue is closed.

**Comment by botandrose** [comment]
@jkwatson Would you mind starting a Jetty server in pure Java and see if it has the same behavior? Should narrow down the problem space to either something in Clojureland or Jetty.

**Comment by jkwatson** [comment]
I can give this a try, yes.

**Comment by jkwatson** [comment]
I have replicated this with a pure java project running jetty.  If I start up the jetty server in the background, I can't kill it with -INT.  sounds like a jetty issue.

**Comment by botandrose** [comment]
Wow, its pretty surprising that something as old and heavily-used as Jetty has a bug like this! Do you know of an alternative Java http server that you can swap with Jetty, and see if the problem disappears?

**Comment by jkwatson** [comment]
bug, or feature? I've been using jetty for stuff for years, and never run into this issue, mostly because I don't usually run my code from scripts that background the actual web process, I'd presume.  And, because I don't SIGINT my web processes pretty much ever.  :)  I'll look to see if the clojure web library lets you plug in tomcat <shudder>.

**Comment by jkwatson** [comment]
I tried this with a plain-jane java process (no jetty) and it appears this is a basic behavior of the JVM. Very odd. I have no idea why this would be happening, and I'm not sure how to google for solutions to it.

**Comment by botandrose** [comment]
Yowza! Can you make a gist?

**Comment by jkwatson** [comment]
There's more.  If I run bin/setup in the foreground, then ctrl-z and background the process, then it *does* respond to SIGINT.  wha????  I'll put together a minimal java example.

**Comment by jkwatson** [comment]
https://gist.github.com/jkwatson/d0c40dc8e4a6be06eb3c

**Comment by jkwatson** [comment]
ok. I've got the answer.  My buddy @breedx2 googled the magic incantation.  See here:  http://unix.stackexchange.com/questions/80975/preventing-propagation-of-sigint-to-parent-process

**Comment by jkwatson** [comment]
Fix is here:  https://github.com/botandrose/eboshi_api_shootout/pull/74
